name = "Librarian Tidy Up the Arcane Library"
home = "https://github.com/Str8UpWHITE64/Librarian-AP"
default_url = "https://github.com/Str8UpWHITE64/Librarian-AP/releases/download/{{version}}/librarian.apworld"

[versions]
"1.1.0" = {}
"2.0.2" = {}
"2.0.3" = {}
